### ISSUE TITLE
Unable to create project with Ubuntu

### ISSUE THREAD

**Issue by PabloLeon** [qiciengine/qiciengine#1]
I can't create a new project in Chrome running on Ubuntu 15.04. My version is qiciengine-1.0.3.
Should Linux work or is it currently not supported?

In case it helps here is the log:

Please enter this url in browser:

http://127.0.0.1:5002/Project.html

New connection.
-----> QUERY_SETTINGS
-----> GET_PLATFORM
-----> GET_USER_HOME_DIR
-----> RECENT_OPEN
-----> GET_USER_HOME_DIR
-----> CHECK_FOR_UPDATES
-----> RECENT_OPEN
New connection.
-----> LIST_DIR
cmd：LIST_DIR，exception：Error: ENOENT, no such file or directory '/Volumes'
Error: ENOENT, no such file or directory '/Volumes'
    at Object.fs.readdirSync (evalmachine.<anonymous>:659:18)
    at listDir (/home/pablo/Documents/gameprojects/qiciengine-1.0.3/editorservice/cmd/LIST_DIR.js:39:12)
    at Object.M.COMMAND.registerCmd.main (/home/pablo/Documents/gameprojects/qiciengine-1.0.3/editorservice/cmd/LIST_DIR.js:87:16)
    at clazz.dispatch (/home/pablo/Documents/gameprojects/qiciengine-1.0.3/editorservice/socket/Command.js:121:33)
    at Socket.<anonymous> (/home/pablo/Documents/gameprojects/qiciengine-1.0.3/editorservice/socket/Command.js:97:14)
    at Socket.EventEmitter.emit (events.js:98:17)
    at Socket.onevent (/home/pablo/Documents/gameprojects/qiciengine-1.0.3/node_modules/socket.io/lib/socket.js:330:8)
    at Socket.onpacket (/home/pablo/Documents/gameprojects/qiciengine-1.0.3/node_modules/socket.io/lib/socket.js:290:12)
    at Client.ondecoded (/home/pablo/Documents/gameprojects/qiciengine-1.0.3/node_modules/socket.io/lib/client.js:193:14)
    at Decoder.Emitter.emit (/home/pablo/Documents/gameprojects/qiciengine-1.0.3/node_modules/component-emitter/index.js:134:20)
-----> LIST_DIR
-----> LIST_DIR
-----> LIST_DIR
-----> CREATE_PROJECT
cmd：CREATE_PROJECT，exception：TypeError: Object #<Object> has no method 'isAbsolute'
TypeError: Object #<Object> has no method 'isAbsolute'
    at clazz.createProject (/home/pablo/Documents/gameprojects/qiciengine-1.0.3/editorservice/module/Project.js:32:15)
    at Object.M.COMMAND.registerCmd.main (/home/pablo/Documents/gameprojects/qiciengine-1.0.3/editorservice/cmd/CREATE_PROJECT.js:10:29)
    at clazz.dispatch (/home/pablo/Documents/gameprojects/qiciengine-1.0.3/editorservice/socket/Command.js:121:33)
    at Socket.<anonymous> (/home/pablo/Documents/gameprojects/qiciengine-1.0.3/editorservice/socket/Command.js:97:14)
    at Socket.EventEmitter.emit (events.js:98:17)
    at Socket.onevent (/home/pablo/Documents/gameprojects/qiciengine-1.0.3/node_modules/socket.io/lib/socket.js:330:8)
    at Socket.onpacket (/home/pablo/Documents/gameprojects/qiciengine-1.0.3/node_modules/socket.io/lib/socket.js:290:12)
    at Client.ondecoded (/home/pablo/Documents/gameprojects/qiciengine-1.0.3/node_modules/socket.io/lib/client.js:193:14)
    at Decoder.Emitter.emit (/home/pablo/Documents/gameprojects/qiciengine-1.0.3/node_modules/component-emitter/index.js:134:20)
    at Decoder.add (/home/pablo/Documents/gameprojects/qiciengine-1.0.3/node_modules/socket.io-parser/index.js:247:12)

**Comment by linyiwei** [comment]
Currently we just test QICI Engine on Mac OS X and Windows, you can try QICI Engine on those two systems, we will look into the issue and test QICI Engine on more platforms, thanks for catching the problem.

**Comment by linyiwei** [comment]
We fixed this issue in latest QICI Engine 1.0.4 version, Please try the latest version again, thanks! 
https://github.com/qiciengine/qiciengine/blob/master/release-notes.md

**Comment by PabloLeon** [comment]
Thanks for your quick reply and this great project! Unfortunately I still have the same problem in version 1.0.4. Here ist the log:

node ./editorservice/StartService.js                                                           ⏎
Port = 5002
Please enter this url in browser:

http://127.0.0.1:5002/Project.html                                                                                      

New connection.
-----> QUERY_SETTINGS
-----> GET_PLATFORM
-----> GET_USER_HOME_DIR
-----> RECENT_OPEN
-----> CHECK_FOR_UPDATES
-----> RECENT_OPEN
-----> LIST_DIR
-----> LIST_DIR
-----> LIST_DIR
-----> CREATE_PROJECT
cmd：CREATE_PROJECT，exception：TypeError: Object #<Object> has no method 'isAbsolute'
TypeError: Object #<Object> has no method 'isAbsolute'
    at clazz.createProject (/home/pablo/Documents/gameprojects/qiciengine-1.0.4 (1)/editorservice/module/Project.js:32:15)
    at Object.M.COMMAND.registerCmd.main (/home/pablo/Documents/gameprojects/qiciengine-1.0.4 (1)/editorservice/cmd/CREATE_PROJECT.js:10:29)
    at clazz.dispatch (/home/pablo/Documents/gameprojects/qiciengine-1.0.4 (1)/editorservice/socket/Command.js:121:33)
    at Socket.<anonymous> (/home/pablo/Documents/gameprojects/qiciengine-1.0.4 (1)/editorservice/socket/Command.js:97:14)
    at Socket.EventEmitter.emit (events.js:98:17)
    at Socket.onevent (/home/pablo/Documents/gameprojects/qiciengine-1.0.4 (1)/node_modules/socket.io/lib/socket.js:330:8)
    at Socket.onpacket (/home/pablo/Documents/gameprojects/qiciengine-1.0.4 (1)/node_modules/socket.io/lib/socket.js:290:12)
    at Client.ondecoded (/home/pablo/Documents/gameprojects/qiciengine-1.0.4 (1)/node_modules/socket.io/lib/client.js:193:14)
    at Decoder.Emitter.emit (/home/pablo/Documents/gameprojects/qiciengine-1.0.4 (1)/node_modules/component-emitter/index.js:134:20)
    at Decoder.add (/home/pablo/Documents/gameprojects/qiciengine-1.0.4 (1)/node_modules/socket.io-parser/index.js:247:12)
-----> CREATE_PROJECT
cmd：CREATE_PROJECT，exception：TypeError: Object #<Object> has no method 'isAbsolute'
TypeError: Object #<Object> has no method 'isAbsolute'
    at clazz.createProject (/home/pablo/Documents/gameprojects/qiciengine-1.0.4 (1)/editorservice/module/Project.js:32:15)
    at Object.M.COMMAND.registerCmd.main (/home/pablo/Documents/gameprojects/qiciengine-1.0.4 (1)/editorservice/cmd/CREATE_PROJECT.js:10:29)
    at clazz.dispatch (/home/pablo/Documents/gameprojects/qiciengine-1.0.4 (1)/editorservice/socket/Command.js:121:33)
    at Socket.<anonymous> (/home/pablo/Documents/gameprojects/qiciengine-1.0.4 (1)/editorservice/socket/Command.js:97:14)
    at Socket.EventEmitter.emit (events.js:98:17)
    at Socket.onevent (/home/pablo/Documents/gameprojects/qiciengine-1.0.4 (1)/node_modules/socket.io/lib/socket.js:330:8)
    at Socket.onpacket (/home/pablo/Documents/gameprojects/qiciengine-1.0.4 (1)/node_modules/socket.io/lib/socket.js:290:12)
    at Client.ondecoded (/home/pablo/Documents/gameprojects/qiciengine-1.0.4 (1)/node_modules/socket.io/lib/client.js:193:14)
    at Decoder.Emitter.emit (/home/pablo/Documents/gameprojects/qiciengine-1.0.4 (1)/node_modules/component-emitter/index.js:134:20)
    at Decoder.add (/home/pablo/Documents/gameprojects/qiciengine-1.0.4 (1)/node_modules/socket.io-parser/index.js:247:12)

**Comment by linyiwei** [comment]
What's your Node.js version, https://nodejs.org/api/path.html#path_path_isabsolute_path look like you are using the version without path.isAbsolute(path) method.

http://docs.qiciengine.com/manual/Overview/MacInstall.html
If you already have Node.js installed, please update it to latest version. the Node.js versions that QICI Engine supports are:

Any v0.12.x version before io.js merged with Node.js
Any version higher than v4.1 after io.js merged with Node.js

**Comment by PabloLeon** [comment]
yes that was the problem! thank you!
